{% set name = "troposphere" %}
{% set version = "2.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cloudtools/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 0345dfb48ba17920a1b976da0b85df860f44a70dd75121b383eac961a9cece3c

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
  run:
    - cfn-flip >=1.0.2
    - awacs >=0.8
    - python

test:
  imports:
    - troposphere
    - troposphere.helpers
    - troposphere.openstack
  requires:
    - awacs >=0.8

about:
  home: https://github.com/cloudtools/troposphere
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: AWS CloudFormation creation library
  doc_url: https://troposphere.readthedocs.io
  dev_url: https://github.com/cloudtools/troposphere

extra:
  recipe-maintainers:
    - agcopenhaver
    - adbeda
    - rluria14
    - oblute
