travis:
  secure:
    BINSTAR_TOKEN: EAoRCcSbvIoFfUeYd8uj+Gwr/3tI6t8G3frllIpisNWpVJdeMeUQuD+YlqMHifQBSksr5H9VtNUZ4XkUEiBCwCS0IK0rshd2I3U5sVWtswLzxa7+Mxm45TjEQ9c4PqOTxXhrSnUlIWDIRR/P7K6KK9noidD6GWxmuxflnr0e3cCuiznEsAxKB6NX5RB9DG9lx2VyQf84qjFFd0l6sOgKPys+v4tZHx+npH095WBMh321jxCCYEoGRPavHUgBIJx4yATwQjdM3bw2CK4jj4hbdIk4gupoJ7X+TFMUSpNAMUGTBEipDghJhEOQRDKuBkkVJeUPaNMn41OEs4efk0xNZm6xcn2K+vFlHKdNWlK8ymVf3/TyLRSIVJWH3Ybfb8j0WQYj4pdBsBkIAFE4ucF/SVAe1/ioaaeLyf0bLFYtjT8VjjQA53YWuEVQWys7jcsFk2Q3yHVyqC1ZJ4ngXoJ4dzFlq8T/QWKocmp+CVNYcsV5t9nZyn5DNnD8xlN9SqiuRfv8VG3RV7IO9AWIkM8d68psmWMIVyiV9Ts3CB28PbUuFpk1UqjY53oK5d2qHpEazNmO7srVtDavnV6AdG1guwUaFAJn6Bh1o1x2Nxl3H8oFE1Ij77ZUKFD6kCN4v5T5ycLBLzbJAWzIRTRW4cFKgaGor+uMv2Kk/8pXielI0IU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
